### ISSUE TITLE
Can't run benchmark, getting an error

### ISSUE THREAD

**Issue by iremlopsum** [A-gambit/CSS-IN-JS-Benchmarks#27]
We've been internally developing a CSS-in-JS solution, and I wanted to make it go through the test.

As I try to run benchmark (haven't yet made any changes) I get

```
async function runTestCase(url) {
      ^^^^^^^^
SyntaxError: Unexpected token function
    at Object.exports.runInThisContext (vm.js:76:16)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ benchmark: `node ./packages/tests/`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @ benchmark script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

Any ideas?

**Comment by Lezhag** [comment]
Different error message, but still can't get the benchmark started


`
....
  run tests...
events.js:136
      throw er; // Unhandled 'error' event
      ^

Error: socket hang up
    at createHangUpError (_http_client.js:330:15)
    at Socket.socketOnEnd (_http_client.js:423:23)
    at Socket.emit (events.js:164:20)
    at endReadableNT (_stream_readable.js:1054:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ benchmark: `node ./packages/tests/`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @ benchmark script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.`

**Comment by A-gambit** [comment]
@Lezhag and @iremlopsum  which version of the Node.js do you use?

**Comment by Lezhag** [comment]
@A-gambit I tried to run it under Node v9.2.1 and v8.9.3. Both end up hanging up

**Comment by iremlopsum** [comment]
@A-gambit I'm using v6.9.5

**Comment by A-gambit** [comment]
Guys use `v7.9+` version. There is a doc in Contribution guide. Node version is mention in it. So please use appropriate version.
